server:
  port: 3000

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:pig-register}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml
# 数据源
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8

logging:
  level:
    org.springframework.security: trace

